Repository raylway/mango, pull requests merged in 2021-07, with the labels that each got.

#11 bugfix/issue-9 to develop
  .DS_Store
  .gitignore
  .npmignore
  README.md
  bin/cli.js
  bin/lib/convert/convert.js
  bin/lib/index.js
  bin/lib/init/init.js
  bin/lib/locales/empty-leaves.js
  bin/lib/locales/locales.js
  bin/lib/locales/test/dev/locales.config.json
  bin/lib/locales/test/locales/en.default.json
  bin/lib/locales/test/locales/ja.json
  bin/lib/locales/test/locales/zh.json
  bin/lib/utils/_directorys.js
  bin/lib/utils/_fsUtils.js
  bin/lib/version/version.js
  bin/settings/recommended/.eslintignore
  bin/settings/recommended/config.yml
  bin/settings/recommended/package.json
  bin/settings/standard/config.yml
  bin/settings/standard/package.json
  package-lock.json
  package.json
Labels: bug

#12 Added customers directory
  .DS_Store
  bin/lib/build/build.js
  bin/lib/convert/convert.js
  bin/lib/utils/_directorys.js
Labels: bug

#10 bugfix/issue-7 to develop
  bin/lib/build/build.js
  package-lock.json
Labels: bug

#14 Release/v1.0.8
  bin/lib/build/build.js
  package-lock.json
Labels: hotfix, release

#16 Fixed resolution by removing paths from command.
  bin/lib/build/build.js
Labels: bug

#17 Release/v1.0.9
  bin/lib/build/build.js
Labels: release, v1.0.9
