Repository raylway/mango, pull requests merged in 2021-06, with the labels that each got.

#4 gitignore syntax
  bin/settings/recommended/.eslintignore
Labels: bug

#3 Feature/locales
  .DS_Store
  README.md
  bin/cli.js
  bin/lib/locales/empty-leaves.js
  bin/lib/locales/locales.js
  bin/lib/locales/test/dev/locales.config.json
  bin/lib/locales/test/locales/en.default.json
  bin/lib/locales/test/locales/ja.json
  bin/lib/locales/test/locales/zh.json
  package-lock.json
  package.json
Labels: enhancement

#2 feature/version-command
  bin/cli.js
  bin/lib/index.js
  bin/lib/version/version.js
Labels: enhancement

#5 Release/v1.0.6
  .DS_Store
  README.md
  bin/cli.js
  bin/lib/index.js
  bin/lib/locales/empty-leaves.js
  bin/lib/locales/locales.js
  bin/lib/locales/test/dev/locales.config.json
  bin/lib/locales/test/locales/en.default.json
  bin/lib/locales/test/locales/ja.json
  bin/lib/locales/test/locales/zh.json
  bin/lib/version/version.js
  bin/settings/recommended/.eslintignore
  package-lock.json
  package.json
Labels: release
